### ISSUE TITLE
Bot 用パッケージディレクトリのセットアップ

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#2]
# 概要

Story チケット： #5 

以下のディレクトリ内にパッケージをセットアップします。

/packages/dev-team-bot

## タスク
- [x] #11
- ~~NestJS パッケージ追加~~
- ~~Railway のステータスチェック用エンドポイント追加~~

## 参考

- Yarn Docs
  - [Features > workspaces](https://yarnpkg.com/features/workspaces/)
  - [CLI > workspace](https://yarnpkg.com/cli/workspace/)
  - [Configuration > workspaces](https://yarnpkg.com/configuration/manifest#workspaces)
- wagumi/wagumi の bot コード
  https://github.com/wagumi/wagumi/tree/main/packages/bot

## QA 項目

1. `yarn workspaces info` コマンドの実行結果に追加したパッケージ情報が表示されること。

## 作業用スレッド

https://discord.com/channels/914960638365810748/917326728211361843/941915255511089233

**Comment by tomoima525** [comment]
こちらも自分担当します

**Comment by kennyttotheleft** [comment]
下記のタスクは #7 に移譲させていただきますので、
本 Issue からスコープアウトさせていただきました 🙏 
- NestJS パッケージ追加
- Railway のステータスチェック用エンドポイント追加
