### ISSUE TITLE
CI 用 GitHub Action 設定追加

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#25]
# 概要

Story Issue: #23 

GitHub リポジトリでの対象イベント時に CI 処理を実行する GitHub Actions 設定を追加します。
本 PR で CI 実行が成功したらブランチプロテクションを設定させていただきます。

## タスク

- [x] ~~eslint-plugin-prettier パッケージのインストール（lint 処理で必要なため）~~
- [x] 下記の処理を CI 実行する GitHub Actions 設定追加
    - yarn lint
    - yarn test

## 設定情報

対象ブランチ
- main
- development

対象イベント
- push
- pull_request

Node.js バージョン：16.13.2
※ サーバインフラで利用している Railway.app の環境に合わせています。

<img width="420" alt="スクリーンショット 2022-02-24 20 29 48" src="https://user-images.githubusercontent.com/6182830/155516344-d117b9ff-f445-4f84-b20b-b72e00a4e922.png">

## 参考

- [Actions | GitHub](https://github.co.jp/features/actions)
- [aguirresabino/github-actions-with-nestjs](https://github.com/aguirresabino/github-actions-with-nestjs)

## QA 項目

- 対象ブランチで CI 処理が実行されること。
  - development
  - main

## 作業用スレッド

- https://discord.com/channels/914960638365810748/949278688732667935

**Comment by kitakaze-kan** [comment]
担当します!

**Comment by kitakaze-kan** [comment]
@kennyttotheleft 

#25のissueに関してなのですが、 workflowの持たせ方についてご相談させてください。
今回のlint/testの設定yamlファイルの構成&命名として、pachage単位(今回ではdev-team-bot.yml)で持たせるのと、レポジトリ全体(test.ymlなど)で持たせるのではどちらの方が好ましいでしょうか？

現状testコマンドがdev-team-botのpackage.jsonにのみ記載してあるので取り急ぎ前者の構成で良いかと思ったのですが、今後の開発なども踏まえて想定されているものがあればご教授いただけますと幸いです！

**Comment by kennyttotheleft** [comment]
@kitakaze-kan 方向性のご確認ありがとうございます 🙏🙏🙏  
workflow の持たせ方の件、確かにでした ✨ 

> 現状testコマンドがdev-team-botのpackage.jsonにのみ記載してあるので取り急ぎ前者の構成で良いかと思ったのですが、今後の開発なども踏まえて想定されているものがあればご教授いただけますと幸いです！

はいっ、仰られる通りで、可能でしたら `前者のパッケージごと` の方向で進めていただけたら大変助かりますー 🙇‍♂️ 

後者のレポジトリ全体の方に関しましては、今後、もしパッケージが増えてきて、本番リリース前にリポジトリ全体でテストしておいた方が安心、的なニーズが出てきた時に追加するか考えられたらと思います 💨

**Comment by kitakaze-kan** [comment]
@kennyttotheleft 
ありがとうございます！PRさせていただきます！

**Comment by kennyttotheleft** [comment]
メモ
下記 Issue タスクは、パッケージ非推奨のため対応なしとなりました。

`eslint-plugin-prettier パッケージのインストール`

経緯につきましては、下記の PR コメントをご参照ください。
https://github.com/wagumi/community-bot/pull/35#issuecomment-1059705712
