### ISSUE TITLE
デバッグメッセージ出力機能

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#26]
# 概要

Story Issue: #23 

Bot からのメッセージにデバッグ情報を追加する機能を開発します。
Railway.app のサーバ環境変数を利用してデバッグ情報を作成ください。

## タスク

- [x] Bot メッセージへのデバッグ情報追加処理を実装

### 設定情報

デバッグ情報を追加する対象ブランチ
- main 以外

## 参考

- [Railway Docs > Railway Provided Variables](https://docs.railway.app/develop/variables#railway-provided-variables)
- 初代 Bot のデバッグコード（[wagumi/wagumi の Bot デバッグ用コード](https://github.com/wagumi/wagumi/blob/3bdf2c4d8b6b2c9b115087f3977e36f24ce94bbe/packages/bot/src/lib/debugUtil.ts#L31-L42)）

参考 Bot の動作例
<img width="388" alt="スクリーンショット 2022-02-24 20 47 56" src="https://user-images.githubusercontent.com/6182830/155518790-59aa963d-43ad-4690-8c60-95d136be8d4b.png">

## QA 項目

- development 環境からの Bot メッセージにデバッグ情報が追加されていること。
- 本番環境からの Bot メッセージにデバッグ情報が追加されていないこと。

## 作業用スレッド

- TBD

**Comment by kitakaze-kan** [comment]
担当します!
