### ISSUE TITLE
ユニットテストケース追加

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#27]
# 概要

Story Issue: #23 

Ping/Pong Bot のユニットテストケースを追加します。

## タスク

- [ ] [botConfig.ts](https://github.com/wagumi/community-bot/blob/main/packages/dev-team-bot/src/bot/config/botConfig.ts) のユニットテストケース追加
- [ ] [message.guard.ts](https://github.com/wagumi/community-bot/blob/main/packages/dev-team-bot/src/bot/guards/message.guard.ts) 用のユニットテストケース追加

## 参考

- TBD

## QA 項目

- [botConfig.ts](https://github.com/wagumi/community-bot/blob/main/packages/dev-team-bot/src/bot/config/botConfig.ts) のユニットテストが成功すること。
- [message.guard.ts](https://github.com/wagumi/community-bot/blob/main/packages/dev-team-bot/src/bot/guards/message.guard.ts) 用のユニットテストが成功すること。

## 作業用スレッド

- https://discord.com/channels/914960638365810748/949278688732667935

**Comment by gentamura** [comment]
@kennyttotheleft 担当します 🙋‍♂️
