### ISSUE TITLE
PJドキュメントの追加

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#28]
# 概要

Story Issue: #23 

プロジェクトに関する下記のドキュメントを追加します。

## タスク

- [x] コントリビューター向け行動規範（CODE_OF_CONDUCT.md）の追加
- [x] セキュリティポリシー（SECURITY.md）の追加

#### コントリビューター向け行動規範

[https://www.contributor-covenant.org/](https://www.contributor-covenant.org/) の日本語最新版 Markdown テキストを下記のサイトから取得し、リポジトリトップに CODE_OF_CONDUCT.md ファイルとして作成ください。

[行動規範翻訳版](https://www.contributor-covenant.org/translations/)

文章内に `[INSERT CONTACT METHOD]` と書かれている箇所がありますので、`[和組 Discord]` に置き換えをお願いいたします。

#### セキュリティポリシー

下記の内容をリポジトリトップに SECURITY.md ファイルとして作成ください。

```
# Security Policy

もし脆弱性を発見された場合は、下記の Issue ページから Bug Issue を作成いただいてご連絡をお願いいたします :pray:
https://github.com/wagumi/community-bot/issues
```

## 参考

- [https://github.com/nestjs/nest/blob/master/CODE_OF_CONDUCT.md](https://github.com/nestjs/nest/blob/master/CODE_OF_CONDUCT.md)
- [https://github.com/nestjs/nest/blob/master/SECURITY.md](https://github.com/nestjs/nest/blob/master/SECURITY.md)

## QA 項目

- 各ドキュメントが追加されていること。
  - コントリビューター向け行動規範（CODE_OF_CONDUCT.md）
  - セキュリティポリシー（SECURITY.md）

## 作業用スレッド

- TBD

**Comment by ukishima** [comment]
担当します

**Comment by kennyttotheleft** [comment]
#36 の development ブランチへのマージが完了しましたので本件クローズとさせていただきます 🙏
