### ISSUE TITLE
Monorepo 用ルートディレクトリのセットアップ

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#3]
# 概要

Story チケット： #5 

## タスク

- [x] package.json 追加
- [x] tsconfig.json 追加
- [x] 共通パッケージを追加
  - husky パッケージ追加

## 参考

- Yarn Docs
  - [Features > workspaces](https://yarnpkg.com/features/workspaces/)
  - [CLI > workspace](https://yarnpkg.com/cli/workspace/)
  - [Configuration > workspaces](https://yarnpkg.com/configuration/manifest#workspaces)
- wagumi/wagumi リポジトリのコード関連
  - https://github.com/wagumi/wagumi
  - tsconfig 関連
    - https://github.com/wagumi/wagumi/blob/main/tsconfig.json
    - https://github.com/wagumi/wagumi/blob/main/tsconfig.base.json
  - husky 関連
    - https://github.com/wagumi/wagumi/tree/main/.husky
    - https://github.com/wagumi/wagumi/blob/main/package.json#L36

## QA 項目

- コード動作がないため、PR がアプルーブされたら 🆗 となります。

## 作業用スレッド

https://discord.com/channels/914960638365810748/917326728211361843/941915255511089233

**Comment by tomoima525** [comment]
対応します
