### ISSUE TITLE
GitHub テンプレート追加

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#30]
# 概要

Story Issue: #23 

下記の用途別に GitHub テンプレートを追加します。

## タスク

- [x] Story Issue
- [x] Task Issue
- [x] Bug report
- [x] Pull Request

### テンプレートの内容

下記トグル内の Markdown テキストをテンプレートとしてご利用ください。

<details>
<summary>Story Issue のテンプレート内容</summary>

```
# 概要

TBD

## タスク

- [ ] TBD

### Issue リスト

- TBD

# 作業用スレッド

- プロジェクト頭出しスレッド
- メンバー募集の Discord スレッド
- プロジェクト進行スレッド

## 参考資料

- TBD
```
</details>

<details>
<summary>Task Issue のテンプレート内容</summary>

```
# 概要

Story Issue: #

TBD

## タスク

- [ ] TBD

### 設定情報

- TBD

## 参考

- TBD

## QA 項目

- TBD

## 作業用スレッド

- TBD
```
</details>

<details>
<summary>Bug Issue のテンプレート内容</summary>

```
# 概要


## 環境情報


## 再現手順

```
</details>

<details>
<summary>Pull Request のテンプレート内容</summary>

```
# 概要


## やったこと


## 備考

```
</details>

## 参考

- [リポジトリ用に Issue テンプレートを設定する](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [リポジトリ用のプルリクエストテンプレートの作成](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
 
## QA 項目

- 各テンプレートが追加されていること。
  - Story Issue
  - Task Issue
  - Bug report
  - Pull Request

## 作業用スレッド

- https://discord.com/channels/914960638365810748/949278688732667935

**Comment by ukishima** [comment]
担当します

**Comment by kennyttotheleft** [comment]
#36 の development ブランチへのマージが完了しましたので本件クローズとさせていただきます 🙏
