### ISSUE TITLE
Discord Bot サンプル追加

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#4]
# 概要

Story チケット： #5 

Discord の設定は Railway に設定済みの下記の環境変数をご利用ください。
設定作業ログ：https://github.com/wagumi/community-bot/issues/1#issuecomment-1035952253

- DISCORD_BOT_TOKEN（文字列）
  和組 Discord にいる Bot のトークンがセットされています。
- DISCORD_DEV_CHANNEL_ALLOWED_LIST：文字列（カンマ区切りのチャンネル ID リスト）
  team-dev-test のチャンネル ID がセットされています。
- DISCORD_GUILD_ID：文字列
  和組 Discord のギルド ID がセットされています。

## タスク

- [ ] !ping のメッセージに pong と返事をする処理を実装

## 参考

- [discord.js](https://discord.js.org/#/)
- [Railway でサンプルアプリをデプロイしてみる](https://www.notion.so/Railway-2d20bc5219d94ae5a0ec09cb729d0e12)
- [Discord Bot サンプルハンズオン](https://www.notion.so/Discord-Bot-1211f62482e048eca0b539a0878dbdf7)
- wagumi/wagumi の bot コード
  https://github.com/wagumi/wagumi/tree/main/packages/bot

## QA 項目

- 和組 Discord チャンネルの team-dev-test で !ping のメッセージに pong と bot が返事をすることを確認

## 作業用スレッド

https://discord.com/channels/914960638365810748/917326728211361843/941915255511089233

**Comment by kitakaze-kan** [comment]
対応します！
