### ISSUE TITLE
NestJS 追加

### ISSUE THREAD

**Issue by kennyttotheleft** [wagumi/community-bot#7]
# 概要

Story チケット： #5 

## タスク

- [x] NestJS パッケージの追加
- [x] サイトルート画面用表示処理追加
  - Path `/` へアクセスが来たら、 `Hello, this is 和組 community bot` と表示する処理を追加ください。
  - ポート指定には、 process.env.PORT を指定ください（Railway.app 仕様へ対応するため）。
- [x] ステータスチェック用レスポンス処理追加（/ping）
  - Path `/ping` へアクセスが来たら、`pong` と表示する処理を追加ください。
- [x] Railway デプロイ用の Procfile 追加とデプロイ用の npm scripts を追加（要相談）

## 参考

- [NestJS Docs > First steps](https://docs.nestjs.com/first-steps)
- wagumi/wagumi リポジトリのコード関連
  - https://github.com/wagumi/wagumi/blob/main/packages/airdrop/tsconfig.json#L20

## QA 項目

- PR用のプレビュー環境での動作確認
  - Path `/` へアクセスしたら、 `Hello, this is 和組 community bot` と表示されることを確認
  - Path '/ping' へアクセスしたら、 `pong` と表示されることを確認

## 作業用スレッド

https://discord.com/channels/914960638365810748/917326728211361843/941915255511089233

**Comment by yorozunouchu** [comment]
こちら担当します。

**Comment by kennyttotheleft** [comment]
## Railway デプロイ用の Procfile と npm スクリプトについて

相談の結果、下記となりました。
- npm スクリプト：npm run deploy
- Procfile：作る（ファイル内容は、 `web: npm run deploy`）

### 関連する Railway 設定の追加について

上記内容にあわせて Railway 設定を追加しておきました 💨 

|デプロイ対象ディレクトリ|デプロイコマンド|
|---|---|
|<img width="320" alt="スクリーンショット 2022-02-13 7 24 56" src="https://user-images.githubusercontent.com/6182830/153730812-ba842b56-da4c-4aa0-9334-11f42e235c57.png">|<img width="320" alt="スクリーンショット 2022-02-13 7 25 41" src="https://user-images.githubusercontent.com/6182830/153730832-074a0725-3a4f-4137-a64e-4ff08ba7edde.png">|

あわせて、ヘルスチェック用のエンドポイント (/path) も設定完了しました。

|ヘルスチェック用エンドポイント|
|---|
|<img width="320" alt="スクリーンショット 2022-02-13 7 25 54" src="https://user-images.githubusercontent.com/6182830/153730837-eb7ec659-270e-472b-bfab-b3adeaa8f99d.png">|

## 参考

- 相談スレッド URL
    https://discord.com/channels/914960638365810748/941915255511089233/941984549154467870
